@AiDevs2Reloaded.Api_HostAddress = http://localhost:5097

GET {{AiDevs2Reloaded.Api_HostAddress}}/helloapi/
Accept: application/json

###

GET {{AiDevs2Reloaded.Api_HostAddress}}/moderate/
Accept: application/json

###

GET {{AiDevs2Reloaded.Api_HostAddress}}/blogger/
Accept: application/json

###

GET {{AiDevs2Reloaded.Api_HostAddress}}/liar/
Accept: application/json

###

GET {{AiDevs2Reloaded.Api_HostAddress}}/inprompt/
Accept: application/json

###

GET {{AiDevs2Reloaded.Api_HostAddress}}/embedding/
Accept: application/json

###

GET {{AiDevs2Reloaded.Api_HostAddress}}/whisper/
Accept: application/json

###